[package]
name = "machineid-rs"
version = "1.2.2"
edition = "2018"
authors = ["Taptiive <aalexius912@gmail.com>"]
description = "Get an encrypted unique MachineID/HWID/UUID. Inspired by .Net DeviceId."
readme = "README.md"
repository = "https://github.com/Taptiive/machineid-rs"
license = "MIT OR Apache-2.0"
keywords = ["hwid", "machineid", "hardware-id", "machineuid", "uuid"]
categories = ["authentication", "config", "accessibility"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.26.7"
whoami = "1.2.3"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.88"
rust-crypto = "0.2.36"
hex = "0.4.3"
uuid = { version = "1.2.2", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
wmi = "0.11.3"
